baseURL = "https://ruheni.dev"
languageCode = "en-us"
title = "Alex Ruheni - learning, building, experimenting, and sharing."
theme = "hello-friend"
paginate = 10

[params] 
 # dir name for blog content
 # list of set content will show up in index page (baseUrl)
  contentTypeName = "posts"
  coverImage = false
  defaultTheme = "dark"
  showReadingTime = true
  # show full page content in RSS feed items
  # default is Description or Summary metadata in front matter
  # rssFullText = true

[languages]
  [languages.en]
    title = "Alex Ruheni - learning, building, experimenting, and sharing."
    subtitle = "Hello there internet stranger👋🏾.\n Welcome to this tiny corner of the interenet - where I share my ideas, thoughts, learning experiences, and experiments"
    keywords = ""
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    minuteReadingTime = "minute read"
    dateFormatList = "January 2, 2006"
    dateFormatSingle = "January 2, 2006"

  [languages.en.params.logo]
    logoText = "Alex Ruheni"
    logoHomeLink = "/"
  
  # TODO: add these pages in future
  [languages.en.menu]
    [[languages.en.menu.main]]
      identifier = "posts"
      name = "Posts"
      url = "/"
  #   [[languages.en.menu.main]]
  #     identifier = "projects"
  #     name = "Projects"
  #     url = "/projects"
    #   [[languages.en.menu.main]]
  #     identifier = "About"
  #     name = "About"
  #     url = "/about"